- block:
  - name: assert > test if default_cron.shell is set correctly
    ansible.builtin.assert:
      that:
        - default_cron.shell is defined
        - default_cron.shell is string
      quiet: yes

  - name: assert > test if default_cron.path is set correctly
    ansible.builtin.assert:
      that:
        - default_cron.path is defined
        - default_cron.path is string
      quiet: yes

  - name: assert > test if default_cron.mailto is set correctly
    ansible.builtin.assert:
      that:
        - default_cron.mailto is defined
        - default_cron.mailto is string
      quiet: yes

  - name: assert > test if cron_jobs is set correctly
    ansible.builtin.assert:
      that:
        - cron_jobs is iterable
      quiet: yes
    when:
      - cron_jobs is defined

  - name: assert > test if item in cron_jobs is set correctly
    ansible.builtin.assert:
      that:
        - item.name is defined
        - item.name is string
        - item.job is defined
        - item.job is string
      quiet: yes
    loop: "{{ cron_jobs }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - cron_jobs is defined

  - name: assert > test if item.minute is set correctly
    ansible.builtin.assert:
      that:
        - item.minute >= 0
        - item.minute <= 59
      quiet: yes
    loop: "{{ cron_jobs }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - cron_jobs is defined
      - item.minute is defined
      - item.minute is number

  - name: assert > test if item.hour is set correctly
    ansible.builtin.assert:
      that:
        - item.hour >= 0
        - item.hour <= 23
      quiet: yes
    loop: "{{ cron_jobs }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - cron_jobs is defined
      - item.hour is defined
      - item.hour is number

  - name: assert > test if item.weekday is set correctly
    ansible.builtin.assert:
      that:
        - item.weekday >= 0
        - item.weekday <= 6
      quiet: yes
    loop: "{{ cron_jobs }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - cron_jobs is defined
      - item.weekday is defined
      - item.weekday is number

  run_once: yes
  delegate_to: localhost
  tags: cron_assert
