
- block:
## remplacer par un template
  - name: lineinfile > configure shell
    ansible.builtin.lineinfile:
      path:   "{{ cron.configuration }}"
      line:   "SHELL={{ default_cron.shell }}"
      regexp: "^SHELL"
      create: yes
      mode:   "0600"
    notify: restart cron

  - name: configure path
    ansible.builtin.lineinfile:
      path:   "{{ cron.configuration }}"
      line:   "PATH={{ default_cron.path }}"
      regexp: "^PATH"
      create: yes
      mode:   "0600"
    notify: restart cron

  - name: Configure mailto
    ansible.builtin.lineinfile:
      path: "{{ cron.configuration }}"
      line: "MAILTO={{ default_cron.mailto }}"
      regexp: "^MAILTO"
      create: yes
      mode: "0600"
    notify:
      - restart cron
## fin template

  become: yes
  tags: cron_config
