- block:
## remplace by template
  - name: lineinfile > configure shell
    lineinfile:
      path:   "{{ cron.configuration }}"
      line:   "SHELL={{ default_cron.shell }}"
      regexp: "^SHELL"
      create: yes
      mode:   "0600"
    notify: "handler | service > restart cron"

  - name: configure path
    lineinfile:
      path:   "{{ cron.configuration }}"
      line:   "PATH={{ default_cron.path }}"
      regexp: "^PATH"
      create: yes
      mode:   "0600"
    notify: "handler | service > restart cron"

  - name: Configure mailto
    lineinfile:
      path: "{{ cron.configuration }}"
      line: "MAILTO={{ default_cron.mailto }}"
      regexp: "^MAILTO"
      create: yes
      mode: "0600"
    notify: "handler | service > restart cron"
## end template

  tags: cron_config
