- block:
  - name: cron > add cron jobs
    cron:
      name:         "{{ item.name }}"
      job:          "{{ item.job  }}"
      minute:       "{{ item.minute       | default(omit) }}"
      hour:         "{{ item.hour         | default(omit) }}"
      day:          "{{ item.day          | default(omit) }}"
      month:        "{{ item.month        | default(omit) }}"
      weekday:      "{{ item.weekday      | default(omit) }}"
      special_time: "{{ item.special_time | default(omit) }}"
      user:         "{{ item.user         | default(omit) }}"
      disabled:     "{{ item.disabled     | default(omit) }}"
      cron_file:    "{{ item.cron_file    | default(omit) }}"
      env:          "{{ item.env          | default(omit) }}"
      value:        "{{ item.value        | default(omit) }}"
      insertafter:  "{{ item.insertafter  | default(omit) }}"
      insertbefore: "{{ item.insertbefore | default(omit) }}"
      backup:       "{{ item.backup       | default(omit) }}"
      reboot:       "{{ item.reboot       | default(omit) }}"
      state:        "{{ item.state        | default('present') }}"
    loop: "{{ cron_jobs }}"

  # - name: template > generate needed script files
  #   template:
  #     src:   "{{ item.src}}"
  #     dest:  "/{{ item.dest }}"
  #     owner: "{{ item.owner | default('root') }}"
  #     group: "{{ item.group | default('root') }}"
  #     mode:  "{{ item.mode  | default('0750') }}"
  #   loop: "{{ cron_files }}"

  tags: cron_jobs
