- block:
  - ansible.builtin.import_tasks: assert.yml

  - ansible.builtin.import_tasks: packages.yml

  - ansible.builtin.import_tasks: config.yml

  - ansible.builtin.import_tasks: service.yml

  - ansible.builtin.import_tasks: cron_jobs.yml

  become: true
  tags: cron
