- block:
  - import_tasks: assert.yml

  - import_tasks: packages.yml

  - import_tasks: config.yml

  - import_tasks: service.yml

  - import_tasks: cron_jobs.yml

  - import_tasks: cron_vars.yml

  become_user: root
  tags: cron
