
- block:
  - name: import_task > assert.yml
    ansible.builtin.import_tasks: assert.yml
    run_once: yes
    delegate_to: localhost

  - import_tasks: install.yml

  - import_tasks: config.yml

  - import_tasks: service.yml

  - import_tasks: cron_jobs.yml

  tags: cron
