
- block:
  - include_tasks: "{{ ansible_os_family }}.yml"

  - name: cron > insert crons
    cron:
      name:       "{{ item.name }}"
      user:       "{{ item.user }}"
      job:        "{{ item.job }}"
      minute:     "{{ item.minute | default('*') }}"
      hour:       "{{ item.hour | default('*') }}"
      day:        "{{ item.day | default('*') }}"
      month:      "{{ item.month | default('*') }}"
      weekday:    "{{ item.weekday | default('*') }}"
      disabled:   "{{ item.disabled | default('no') }}"
      state:      "{{ item.state | default('present') }}"
      cron_file:  "{{ item.cron_file | default('ecritel') }}"
    loop: "{{ cron_list }}"
    loop_control:
      label: "{{ item.name }}"
    when:
      - cron_list is defined
      - cron_list | length > 0

  - name: template > copy needed script files
    template:
      src:    "{{ item.src }}.j2"
      dest:   "/{{ item.dest }}"
      owner:  "{{ item.owner | default('root') }}"
      group:  "{{ item.group | default('root') }}"
      mode:   "{{ item.mode  | default('0750') }}"
    loop: "{{ cron_files }}"
    when:
      - cron_files is defined
      - cron_files | length > 0

  # buluma/ansible-role-cron
  - import_tasks: vars.yml
    tags:
      - system
      - cron
      - vars
      - cron-vars

  - import_tasks: install.yml
    tags:
      - system
      - cron
      - install
      - cron-install

  - import_tasks: config.yml
    tags:
      - system
      - cron
      - config
      - cron-config

  - import_tasks: service.yml
    tags:
      - system
      - cron
      - service
      - cron-service
  tags: cron
