
- block:
  - name: systemd > ensuring unmasked service
    ansible.builtin.systemd:
      name:   "{{ cron.service }}"
      masked: no
    when: ansible_service_mgr == "systemd"

  - name: service > start and enable cron
    ansible.builtin.service:
      name:    "{{ cron.service }}"
      state:   "{{ default_cron.service_state   }}"
      enabled: "{{ default_cron.service_enabled }}"
    when:
      - cron.service is defined
      - cron.service | length

  become: yes
  tags: cron_service
