- block:
  - name: systemd > ensuring unmasked service
    systemd:
      name:   "{{ cron.service }}"
      masked: no
    when: ansible_service_mgr == "systemd"

  - name: service > start and enable cron
    service:
      name:    "{{ cron.service }}"
      state:   "{{ cron_service_state   }}"
      enabled: "{{ cron_service_enabled }}"

  tags: cron_service
