- name: handler | service > restart cron
  service:
    name: "{{ cron.service }}"
    state: restarted
  when:
    - cron.service | length
    - not ansible_check_mode
    - default_cron.service_state != 'stopped'
